from .....direct.table.props.table_properties import TblAuto as TblAuto
from .....direct.table.props.table_properties import TblCenterWidth as TblCenterWidth
from .....direct.table.props.table_properties import TblLeft as TblLeft
from .....direct.table.props.table_properties import TblRight as TblRight
from .....direct.table.props.table_properties import TblCenterLeft as TblCenterLeft
from .....direct.table.props.table_properties import TblFromLeft as TblFromLeft
from .....direct.table.props.table_properties import TblFromLeftWidth as TblFromLeftWidth
from .....direct.table.props.table_properties import TblManualLeftRight as TblManualLeftRight
from .....direct.table.props.table_properties import TblRelLeftByWidth as TblRelLeftByWidth
from .....direct.table.props.table_properties import TblRelFromLeft as TblRelFromLeft
from .....direct.table.props.table_properties import TblRelRightByWidth as TblRelRightByWidth
from .....direct.table.props.table_properties import TblRelCenter as TblRelCenter
from .....direct.table.props.table_properties import TableAlignKind as TableAlignKind
from .....direct.table.props.table_properties import TableProperties as TableProperties
