from .....direct.table.props.table_properties import TblAuto as TblAuto
from .....direct.table.props.table_properties import TblWidth as TblWidth
from .....direct.table.props.table_properties import TblLeft as TblLeft
from .....direct.table.props.table_properties import TblRight as TblRight
from .....direct.table.props.table_properties import TblCenter as TblCenter
from .....direct.table.props.table_properties import TblFromLeft as TblFromLeft
from .....direct.table.props.table_properties import TblFromLeftWidth as TblFromLeftWidth
from .....direct.table.props.table_properties import TblManual as TblManual
from .....direct.table.props.table_properties import TblRelLeft as TblRelLeft
from .....direct.table.props.table_properties import TblRelFromLeft as TblRelFromLeft
from .....direct.table.props.table_properties import TblRelRight as TblRelRight
from .....direct.table.props.table_properties import TblRelCenter as TblRelCenter
from .....direct.table.props.table_properties import TableProperties as TableProperties
