from enum import Flag


class FormatterTableItemKind(Flag):
    NONE = 0
    END_COL_RIGHT_STRIP = 1 << 0
    END_COL_LEFT_STRIP = 1 << 1
    START_COL_RIGHT_STRIP = 1 << 2
    START_COL_LEFT_STRIP = 1 << 3
    COL_RIGHT_STRIP = 1 << 4
    COL_LEFT_STRIP = 1 << 5
    START_COL_STRIP = START_COL_LEFT_STRIP | START_COL_RIGHT_STRIP
    END_COL_STRIP = END_COL_LEFT_STRIP | END_COL_RIGHT_STRIP
